### ISSUE TITLE
Why does it output the paring on terminal? 

### ISSUE THREAD

**Issue by FionnD** [jmarkowski/secret-santa#5]
Great project! Just what I wanted, so thank you :)

One question, when I test the script, why does it output the paring? Surely these should be secret? 
```
(secret_santa) fionn@dsiadmins-Air secret_santa % python send-letters.py 
Fionn        -> Sarah
Sarah        -> Fionn
```

**Comment by jmarkowski** [comment]
Thanks for bringing this to my attention!

Yes, the pairings are secret, they were displayed for testing reasons, but when the emails are sent the pairings don't show. I'm updating it now to never display the pairings in stdout to prevent this confusion again.
