### ISSUE TITLE
Uh oh, something failed: Unknown santa in incompatible list: Please check spelling

### ISSUE THREAD

**Issue by ghost** [jmarkowski/secret-santa#9]
Hi,

Great app, but incompatible part does not work.

Not sure why, but this always happens - even with your demo config.

**Comment by jmarkowski** [comment]
Hi,

Can you share what you have in the incompatibles section?

**Comment by jmarkowski** [comment]
This error would only be raised if there's "incompatibles" references the name of a Santa from the "santas" list which doesn't exist.

I can only suggest double checking the spelling and making sure the names under "incompatibles" match exactly any of the names in the "santas" list.
